# Generated by Django 4.1 on 2022-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.TextField(choices=[('pending', 'Pending'), ('in_game', 'In Game'), ('done', 'Done')], default='pending')),
            ],
        ),
    ]
