version: '3.4'

services:
  app:
    command: python -m pytest -v test/
    build:
      target: test
    environment:
      SECRET: fC3_dIulW3yvSolZJ4p7VmeQGNwHAGnXe0_wK-ZrMm4=
      DB_URI: postgres://test:test@db:5432/test
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
