version: '3.4'

services:
  app:
    command: python -m pytest -v test/
    build:
      target: test
    environment:
      DB_URI: postgres://test:test@db:5432/test
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
    volumes: []
    ports: []
