version: '3.4'

services:
  app:
    command: adev runserver .
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - '4444:8000'
    volumes:
      - .:/server
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      DB_URI: postgres://${APP_DB_USERNAME}:${APP_DB_PASSWORD}@db:5432/${APP_DB_DATABASE}
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db:
