services:
  gateway:
    ports:
      - '8000:8000'
    build:
      target: dev
    volumes:
      - ../gateway/:/gateway

  profiler:
    build:
      target: dev
    ports:
      - '50051:50051'
    volumes:
      - ../profiler:/profiler

  ttt_online:
   build:
     target: dev
     dockerfile: ops/ttt-online/Dockerfile
   ports:
     - '4444:8000'
   volumes:
     - ../ttt-online/:/server

  db:
    env_file:
      - postgres/environment
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/multi_db.sh:/docker-entrypoint-initdb.d/multi_db.sh
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]

volumes:
  db:
