services:
  django:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../ttt-online-django/:/server
    ports:
      - '8000:8000'
    env_file:
      - django/environment

  app:
    build:
      target: dev
    ports:
      - '4444:8000'
    volumes:
      - ../ttt-online/:/server

  db:
    env_file:
      - postgres/environment
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/multi_db.sh:/docker-entrypoint-initdb.d/multi_db.sh
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]

volumes:
  db:
