services:
  app:
    command: sh -c "pgrate -p ${MIGRATIONS_FOLDER} -d ${TEST_DB_URI} && python -m pytest -vv test/integration"
    build:
      target: test
      dockerfile: ops/Dockerfile
    environment:
      SECRET: ${SECRET}
      DB_URI: ${TEST_DB_URI}
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
