services:
  app:
    command: sh -c "pgrate -p ${MIGRATIONS_FOLDER} -d ${DB_URI} && adev runserver ."
    build:
      context: ..
      target: dev
      dockerfile: ops/Dockerfile
    environment:
      SECRET: ${SECRET}
      DB_URI: ${DB_URI}
    ports:
      - '4444:8000'
    volumes:
      - ..:/server
  db:
    environment:
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $APP_DB_USERNAME" ]

volumes:
  db:
