services:
  app:
    build:
      target: dev
    ports:
      - '4444:8000'
    volumes:
      - ../ttt-online/:/server
    env_file:
      - ttt-online/dev-environment

  db:
    env_file:
      - postgres/environment
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]

volumes:
  db:
