services:
  app:
    command: sh -c "pgrate -p ${MIGRATIONS_FOLDER} -d ${TEST_DB_URI} && python -m pytest -vv test/"
    build:
      context: ..
      target: test
      dockerfile: ops/Dockerfile
    environment:
      SECRET: fC3_dIulW3yvSolZJ4p7VmeQGNwHAGnXe0_wK-ZrMm4=
      DB_URI: ${TEST_DB_URI}
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
