services:
  app:
    build:
      target: test-integration
    env_file:
      - ttt-online/test-environment
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
